version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-docker
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www/html
  composer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
